language: swift
os : osx

addons:
  browserstack:
    username: "touseefiosdev1"
    access_key: "tsKsjvTpmoyh86zyH9nb"
    
    
script:
    - "curl -H 'Content-Type: application/json' -X POST  -d '{\"app\": \"bs://d62912336f226a770d80395c56d6105a05dd22d2\", \"deviceLogs\" : \"true\", \"testSuite\": \"bs://b3e59c8fd029157112f5f0ee0dbb24aec4f1a120\", \"devices\" : [\"iPhone 11 Pro Max-13\"]}' \"https://api-cloud.browserstack.com/app-automate/xcuitest/build\"  -u \"touseefiosdev1:tsKsjvTpmoyh86zyH9nb\""
