language: swift
os: osx
addons:
  browserstack:
    username: "touseefiosdev1"
    access_key: "tsKsjvTpmoyh86zyH9nb"
    
script:
  - curl -u "touseefiosdev1:tsKsjvTpmoyh86zyH9nb" -X POST "https://api-cloud.browserstack.com/app-automate/xcuitest/test-suite" -F "file=@Outdoor360/UITestCases/Login/Login-Runner.zip"
  
